_target_: src.models.gan_module.GAN

generator:
  _target_: src.models.gan_components.dc_gan_v2.Generator
  channels: 1
  height: 32
  width: 32
  latent_dim: 100
discriminator:
  _target_: src.models.gan_components.dc_gan_v2.Discriminator
  channels: 1
  height: 32
  width: 32
lr: 0.0002
b1: 0.5
b2: 0.999
